// ============================================================
// UNIEVENT — Phase 4B Admin Users Fake Data
// ============================================================

export type UserRole =
  | "admin"
  | "doyen"
  | "responsable_evenements"
  | "president_club"
  | "etudiant";

export type UserStatus = "active" | "inactive" | "suspended";

export interface AdminUser {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  role: UserRole;
  status: UserStatus;
  isPremium: boolean;
  department: string;
  joinedAt: string;
  lastSeen: string;
  eventsCreated: number;
  eventsAttended: number;
  clubsJoined: string[];
  phone?: string;
  studentId?: string;
  bio?: string;
  verified: boolean;
}

export const ROLE_LABELS: Record<UserRole, string> = {
  admin: "Administrateur",
  doyen: "Doyen",
  responsable_evenements: "Resp. Événements",
  president_club: "Président Club",
  etudiant: "Étudiant",
};

export const ROLE_COLORS: Record<UserRole, string> = {
  admin: "bg-purple-500/15 text-purple-400 border-purple-500/30",
  doyen: "bg-amber-500/15 text-amber-400 border-amber-500/30",
  responsable_evenements: "bg-blue-500/15 text-blue-400 border-blue-500/30",
  president_club: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  etudiant: "bg-slate-500/15 text-slate-400 border-slate-500/30",
};

export const STATUS_COLORS: Record<UserStatus, string> = {
  active: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  inactive: "bg-slate-500/15 text-slate-400 border-slate-500/30",
  suspended: "bg-red-500/15 text-red-400 border-red-500/30",
};

export const STATUS_LABELS: Record<UserStatus, string> = {
  active: "Actif",
  inactive: "Inactif",
  suspended: "Suspendu",
};

const DEPARTMENTS = [
  "Informatique",
  "Mathématiques",
  "Physique",
  "Génie Civil",
  "Génie Électrique",
  "Chimie",
  "Biologie",
  "Administration",
];

const CLUBS = [
  "Club Tech FST",
  "Club Informatique",
  "Club Robotique",
  "Club FinTech",
  "Club Dev",
  "Club Sciences",
  "Club Maths",
  "Club Art",
];

export const ADMIN_USERS: AdminUser[] = [
  {
    id: "u001",
    name: "Mohammed Fassi",
    email: "m.fassi@admin.fst-settat.ma",
    role: "admin",
    status: "active",
    isPremium: true,
    department: "Administration",
    joinedAt: "2023-09-01T08:00:00Z",
    lastSeen: "2026-05-06T10:30:00Z",
    eventsCreated: 0,
    eventsAttended: 45,
    clubsJoined: [],
    phone: "+212 6 61 00 00 01",
    verified: true,
    bio: "Administrateur principal de la plateforme UniEvent.",
  },
  {
    id: "u002",
    name: "Alaoui Rachid",
    email: "r.alaoui@doyen.fst-settat.ma",
    role: "doyen",
    status: "active",
    isPremium: true,
    department: "Administration",
    joinedAt: "2023-09-01T08:00:00Z",
    lastSeen: "2026-05-05T15:00:00Z",
    eventsCreated: 2,
    eventsAttended: 120,
    clubsJoined: [],
    phone: "+212 6 61 00 00 02",
    verified: true,
    bio: "Doyen de la faculté FST Settat.",
  },
  {
    id: "u003",
    name: "Fatima Zahra El Idrissi",
    email: "fz.elidrissi@fst-settat.ma",
    role: "responsable_evenements",
    status: "active",
    isPremium: true,
    department: "Administration",
    joinedAt: "2023-10-15T08:00:00Z",
    lastSeen: "2026-05-06T09:00:00Z",
    eventsCreated: 18,
    eventsAttended: 87,
    clubsJoined: [],
    phone: "+212 6 61 00 00 03",
    verified: true,
    bio: "Responsable de la coordination des événements universitaires.",
  },
  {
    id: "u004",
    name: "Amina Tazi",
    email: "a.tazi@etu.fst-settat.ma",
    role: "president_club",
    status: "active",
    isPremium: true,
    department: "Informatique",
    joinedAt: "2024-09-02T08:00:00Z",
    lastSeen: "2026-05-06T11:00:00Z",
    eventsCreated: 12,
    eventsAttended: 34,
    clubsJoined: ["Club Tech FST", "Club Informatique"],
    studentId: "ETU-2024-0041",
    verified: true,
    bio: "Présidente du Club Tech FST, passionnée par l'IA et le développement web.",
  },
  {
    id: "u005",
    name: "Omar Benkirane",
    email: "o.benkirane@etu.fst-settat.ma",
    role: "president_club",
    status: "active",
    isPremium: true,
    department: "Informatique",
    joinedAt: "2024-09-02T08:00:00Z",
    lastSeen: "2026-05-05T18:00:00Z",
    eventsCreated: 9,
    eventsAttended: 28,
    clubsJoined: ["Club Informatique"],
    studentId: "ETU-2024-0089",
    verified: true,
    bio: "Président du Club Informatique.",
  },
  {
    id: "u006",
    name: "Yasmine Benali",
    email: "y.benali@etu.fst-settat.ma",
    role: "etudiant",
    status: "active",
    isPremium: false,
    department: "Mathématiques",
    joinedAt: "2026-05-06T09:15:00Z",
    lastSeen: "2026-05-06T09:15:00Z",
    eventsCreated: 0,
    eventsAttended: 0,
    clubsJoined: [],
    studentId: "ETU-2026-1284",
    verified: false,
    bio: "",
  },
  {
    id: "u007",
    name: "Youssef Alami",
    email: "y.alami@etu.fst-settat.ma",
    role: "president_club",
    status: "active",
    isPremium: true,
    department: "Génie Électrique",
    joinedAt: "2024-09-03T08:00:00Z",
    lastSeen: "2026-05-04T20:00:00Z",
    eventsCreated: 6,
    eventsAttended: 19,
    clubsJoined: ["Club Robotique"],
    studentId: "ETU-2024-0112",
    verified: true,
    bio: "Président du Club Robotique FST.",
  },
  {
    id: "u008",
    name: "Nour El Houda Berrada",
    email: "n.berrada@etu.fst-settat.ma",
    role: "president_club",
    status: "active",
    isPremium: true,
    department: "Mathématiques",
    joinedAt: "2024-09-10T08:00:00Z",
    lastSeen: "2026-05-03T17:00:00Z",
    eventsCreated: 5,
    eventsAttended: 22,
    clubsJoined: ["Club FinTech", "Club Maths"],
    studentId: "ETU-2024-0158",
    verified: true,
    bio: "Présidente du Club FinTech.",
  },
  {
    id: "u009",
    name: "Karim Mansouri",
    email: "k.mansouri@etu.fst-settat.ma",
    role: "etudiant",
    status: "active",
    isPremium: false,
    department: "Génie Civil",
    joinedAt: "2025-09-01T08:00:00Z",
    lastSeen: "2026-05-05T14:00:00Z",
    eventsCreated: 0,
    eventsAttended: 7,
    clubsJoined: ["Club Art"],
    studentId: "ETU-2025-0204",
    verified: true,
    bio: "",
  },
  {
    id: "u010",
    name: "Hajar Ouali",
    email: "h.ouali@etu.fst-settat.ma",
    role: "etudiant",
    status: "active",
    isPremium: false,
    department: "Chimie",
    joinedAt: "2025-09-01T08:00:00Z",
    lastSeen: "2026-05-02T11:00:00Z",
    eventsCreated: 0,
    eventsAttended: 12,
    clubsJoined: ["Club Sciences"],
    studentId: "ETU-2025-0267",
    verified: true,
    bio: "",
  },
  {
    id: "u011",
    name: "Saad El Fassi",
    email: "s.elfassi@etu.fst-settat.ma",
    role: "etudiant",
    status: "suspended",
    isPremium: false,
    department: "Informatique",
    joinedAt: "2024-09-01T08:00:00Z",
    lastSeen: "2026-04-10T08:00:00Z",
    eventsCreated: 0,
    eventsAttended: 3,
    clubsJoined: [],
    studentId: "ETU-2024-1047",
    verified: true,
    bio: "Compte suspendu pour comportement inapproprié.",
  },
  {
    id: "u012",
    name: "Zineb Cherkaoui",
    email: "z.cherkaoui@etu.fst-settat.ma",
    role: "etudiant",
    status: "active",
    isPremium: true,
    department: "Physique",
    joinedAt: "2024-09-02T08:00:00Z",
    lastSeen: "2026-05-06T08:30:00Z",
    eventsCreated: 3,
    eventsAttended: 25,
    clubsJoined: ["Club Sciences", "Club Tech FST"],
    studentId: "ETU-2024-0321",
    verified: true,
    bio: "Étudiante en master Physique, impliquée dans plusieurs clubs.",
  },
  {
    id: "u013",
    name: "Anas Roudani",
    email: "a.roudani@etu.fst-settat.ma",
    role: "etudiant",
    status: "inactive",
    isPremium: false,
    department: "Biologie",
    joinedAt: "2023-09-05T08:00:00Z",
    lastSeen: "2025-12-15T10:00:00Z",
    eventsCreated: 0,
    eventsAttended: 4,
    clubsJoined: [],
    studentId: "ETU-2023-0891",
    verified: true,
    bio: "",
  },
  {
    id: "u014",
    name: "Meryem Tahiri",
    email: "m.tahiri@etu.fst-settat.ma",
    role: "etudiant",
    status: "active",
    isPremium: false,
    department: "Génie Électrique",
    joinedAt: "2025-09-03T08:00:00Z",
    lastSeen: "2026-05-04T16:00:00Z",
    eventsCreated: 0,
    eventsAttended: 9,
    clubsJoined: ["Club Robotique"],
    studentId: "ETU-2025-0412",
    verified: true,
    bio: "",
  },
  {
    id: "u015",
    name: "Rachid Bouziani",
    email: "r.bouziani@fst-settat.ma",
    role: "responsable_evenements",
    status: "active",
    isPremium: true,
    department: "Administration",
    joinedAt: "2023-09-01T08:00:00Z",
    lastSeen: "2026-05-05T16:10:00Z",
    eventsCreated: 8,
    eventsAttended: 65,
    clubsJoined: [],
    phone: "+212 6 61 00 00 15",
    verified: true,
    bio: "Responsable des réservations de salles.",
  },
  {
    id: "u016",
    name: "Imane Naciri",
    email: "i.naciri@etu.fst-settat.ma",
    role: "etudiant",
    status: "active",
    isPremium: false,
    department: "Informatique",
    joinedAt: "2026-02-01T08:00:00Z",
    lastSeen: "2026-05-06T07:00:00Z",
    eventsCreated: 0,
    eventsAttended: 2,
    clubsJoined: ["Club Dev"],
    studentId: "ETU-2026-0089",
    verified: true,
    bio: "",
  },
  {
    id: "u017",
    name: "Hamza Ouazzani",
    email: "h.ouazzani@etu.fst-settat.ma",
    role: "etudiant",
    status: "active",
    isPremium: true,
    department: "Mathématiques",
    joinedAt: "2024-09-01T08:00:00Z",
    lastSeen: "2026-05-05T20:00:00Z",
    eventsCreated: 2,
    eventsAttended: 18,
    clubsJoined: ["Club Maths", "Club Dev"],
    studentId: "ETU-2024-0503",
    verified: true,
    bio: "",
  },
  {
    id: "u018",
    name: "Sara Lahlou",
    email: "s.lahlou@etu.fst-settat.ma",
    role: "etudiant",
    status: "active",
    isPremium: false,
    department: "Chimie",
    joinedAt: "2025-09-04T08:00:00Z",
    lastSeen: "2026-05-03T12:00:00Z",
    eventsCreated: 0,
    eventsAttended: 6,
    clubsJoined: ["Club Sciences"],
    studentId: "ETU-2025-0677",
    verified: false,
    bio: "",
  },
  {
    id: "u019",
    name: "Khalid Ziani",
    email: "k.ziani@etu.fst-settat.ma",
    role: "etudiant",
    status: "inactive",
    isPremium: false,
    department: "Génie Civil",
    joinedAt: "2023-09-05T08:00:00Z",
    lastSeen: "2025-06-01T10:00:00Z",
    eventsCreated: 0,
    eventsAttended: 1,
    clubsJoined: [],
    studentId: "ETU-2023-1102",
    verified: true,
    bio: "",
  },
  {
    id: "u020",
    name: "Douaa Bennis",
    email: "d.bennis@etu.fst-settat.ma",
    role: "etudiant",
    status: "active",
    isPremium: false,
    department: "Biologie",
    joinedAt: "2025-09-02T08:00:00Z",
    lastSeen: "2026-05-06T09:45:00Z",
    eventsCreated: 0,
    eventsAttended: 11,
    clubsJoined: ["Club Sciences"],
    studentId: "ETU-2025-0901",
    verified: true,
    bio: "",
  },
];

// ── User Stats Summary ────────────────────────────────────────

export function getUserStats(users: AdminUser[]) {
  return {
    total: users.length,
    active: users.filter((u) => u.status === "active").length,
    inactive: users.filter((u) => u.status === "inactive").length,
    suspended: users.filter((u) => u.status === "suspended").length,
    premium: users.filter((u) => u.isPremium).length,
    admins: users.filter((u) => u.role === "admin").length,
    doyens: users.filter((u) => u.role === "doyen").length,
    presidents: users.filter((u) => u.role === "president_club").length,
    responsables: users.filter((u) => u.role === "responsable_evenements").length,
    etudiants: users.filter((u) => u.role === "etudiant").length,
  };
}
