// ============================================================
// UNIEVENT — Phase 5A: Public Events Data
// ============================================================

import type { EventCategory } from "@/types";

export interface PublicEvent {
  id: string;
  title: string;
  description: string;
  longDescription: string;
  category: EventCategory;
  startDate: string;
  endDate: string;
  isMultiDay: boolean;
  location: string;
  building: string;
  coverUrl: string;
  gallery: string[];
  capacity: number;
  registeredCount: number;
  isFree: boolean;
  price?: number;
  organizerId: string;
  organizerName: string;
  organizerAvatar?: string;
  clubName?: string;
  clubLogo?: string;
  tags: string[];
  speakers: { name: string; role: string; avatar?: string }[];
  isHighlight: boolean;
  status: "upcoming" | "ongoing" | "done";
}

// Unsplash-style placeholder images using picsum
const COVERS = [
  "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
  "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&q=80",
  "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
  "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800&q=80",
  "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80",
  "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
  "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80",
  "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&q=80",
  "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80",
  "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80",
  "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80",
  "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&q=80",
];

const GALLERY = [
  "https://images.unsplash.com/photo-1559223607-a43c990c692c?w=600&q=80",
  "https://images.unsplash.com/photo-1511578314322-379afb476865?w=600&q=80",
  "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600&q=80",
  "https://images.unsplash.com/photo-1542621334-a254cf47733d?w=600&q=80",
  "https://images.unsplash.com/photo-1523301343968-6a6ebf63c672?w=600&q=80",
  "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=600&q=80",
];

export const PUBLIC_EVENTS: PublicEvent[] = [
  {
    id: "evt-001",
    title: "Summit Tech & IA 2026",
    description: "La grande conférence annuelle sur l'Intelligence Artificielle et les technologies du futur.",
    longDescription: `Rejoignez-nous pour une journée immersive au cœur des technologies qui transforment notre monde. Le Summit Tech & IA 2026 rassemble chercheurs, entrepreneurs et étudiants pour explorer les frontières de l'intelligence artificielle, de la robotique et du big data.\n\nAu programme : keynotes inspirantes, ateliers pratiques, démonstrations live et networking avec les leaders du secteur. Une occasion unique d'échanger avec des experts de renommée internationale et de découvrir les dernières innovations.\n\nNe manquez pas cette opportunité de vous positionner à l'avant-garde de la révolution technologique.`,
    category: "conference",
    startDate: "2026-06-15T09:00:00",
    endDate: "2026-06-15T18:00:00",
    isMultiDay: false,
    location: "Amphithéâtre Principal",
    building: "Bâtiment A — Campus Central",
    coverUrl: COVERS[0],
    gallery: GALLERY.slice(0, 4),
    capacity: 400,
    registeredCount: 312,
    isFree: false,
    price: 0,
    organizerId: "org-1",
    organizerName: "Dr. Amina Bensalem",
    clubName: "Club IA & Data Science",
    tags: ["IA", "Machine Learning", "Data", "Innovation"],
    speakers: [
      { name: "Prof. Karim Mansouri", role: "Chercheur MIT" },
      { name: "Leila Hamdani", role: "CEO TechStartup" },
      { name: "Dr. Youssef Benali", role: "Expert en NLP" },
    ],
    isHighlight: true,
    status: "upcoming",
  },
  {
    id: "evt-002",
    title: "Hackathon 48h — Solutions Durables",
    description: "48 heures non-stop pour concevoir des solutions tech en faveur du développement durable.",
    longDescription: `Le Hackathon 48h Solutions Durables est un marathon d'innovation où des équipes de 3 à 5 étudiants relèvent des défis environnementaux concrets. Avec le soutien de partenaires industriels, les participants disposent d'APIs, datasets et mentors pour créer des prototypes fonctionnels.\n\nThèmes : énergie renouvelable, gestion des déchets, agriculture intelligente, mobilité verte. Les 3 meilleures équipes remportent des bourses et des stages dans des entreprises partenaires.`,
    category: "competition",
    startDate: "2026-05-22T18:00:00",
    endDate: "2026-05-24T18:00:00",
    isMultiDay: true,
    location: "Salle Innovation Lab",
    building: "Bâtiment Tech — Aile Est",
    coverUrl: COVERS[1],
    gallery: GALLERY.slice(1, 5),
    capacity: 120,
    registeredCount: 108,
    isFree: true,
    organizerId: "org-2",
    organizerName: "Rania Cherkaoui",
    clubName: "Club Dev & Innovation",
    tags: ["Hackathon", "Développement Durable", "Coding", "Green Tech"],
    speakers: [],
    isHighlight: true,
    status: "upcoming",
  },
  {
    id: "evt-003",
    title: "Atelier Design Thinking",
    description: "Apprenez la méthodologie Design Thinking pour résoudre des problèmes complexes de manière créative.",
    longDescription: `Cet atelier intensif vous plonge dans les 5 étapes du Design Thinking : Empathie, Définition, Idéation, Prototypage et Test. Animé par des praticiens expérimentés, il alterne théorie et exercices pratiques sur des cas réels.\n\nIdéal pour les étudiants en management, ingénierie et design qui souhaitent développer une approche centrée utilisateur dans leurs projets.`,
    category: "atelier",
    startDate: "2026-06-03T14:00:00",
    endDate: "2026-06-03T18:00:00",
    isMultiDay: false,
    location: "Salle Workshop A-204",
    building: "Bâtiment A — 2ème étage",
    coverUrl: COVERS[2],
    gallery: GALLERY.slice(0, 3),
    capacity: 30,
    registeredCount: 28,
    isFree: true,
    organizerId: "org-3",
    organizerName: "Mme. Fatima Zohra",
    clubName: "Club Management & Entrepreneuriat",
    tags: ["Design Thinking", "Créativité", "Innovation", "Management"],
    speakers: [
      { name: "Mme. Fatima Zohra", role: "Coach Design Thinking" },
    ],
    isHighlight: false,
    status: "upcoming",
  },
  {
    id: "evt-004",
    title: "Tournoi Universitaire de Foot 5",
    description: "Le championnat inter-filières de football à 5 revient ! Inscrivez votre équipe et relevez le défi.",
    longDescription: `Le Tournoi de Foot 5 inter-filières est l'événement sportif de l'année ! Ouvert à tous les étudiants, il accueille jusqu'à 16 équipes de 5 joueurs dans une compétition amicale mais intense.\n\nFormat : poules + phases éliminatoires. Trophées pour les 3 premières équipes. Restauration et ambiance festive garanties. Arbitres certifiés pour des matchs dans les règles de l'art.`,
    category: "sportif",
    startDate: "2026-06-07T08:00:00",
    endDate: "2026-06-07T20:00:00",
    isMultiDay: false,
    location: "Terrain Synthétique Ouest",
    building: "Complexe Sportif — Entrée Sud",
    coverUrl: COVERS[3],
    gallery: GALLERY.slice(2, 6),
    capacity: 160,
    registeredCount: 80,
    isFree: true,
    organizerId: "org-4",
    organizerName: "Hamza Lefkir",
    clubName: "Club Sportif Universitaire",
    tags: ["Football", "Sport", "Tournoi", "Compétition"],
    speakers: [],
    isHighlight: false,
    status: "upcoming",
  },
  {
    id: "evt-005",
    title: "Nuit Culturelle des Nations",
    description: "Une soirée inoubliable célébrant la diversité culturelle à travers musiques, danses et gastronomie du monde.",
    longDescription: `La Nuit Culturelle des Nations est le grand rendez-vous multiculturel de l'université. Chaque association étudiante présente la culture de son pays d'origine : costumes traditionnels, performances artistiques, stands gastronomiques et démonstrations artisanales.\n\nUne invitation au voyage et au partage, pour renforcer les liens entre étudiants du monde entier. Ouvert à tous, gratuit, avec buffet international inclus.`,
    category: "culturel",
    startDate: "2026-06-20T19:00:00",
    endDate: "2026-06-20T23:30:00",
    isMultiDay: false,
    location: "Aula Magna",
    building: "Bâtiment Principal",
    coverUrl: COVERS[5],
    gallery: GALLERY.slice(0, 5),
    capacity: 500,
    registeredCount: 234,
    isFree: true,
    organizerId: "org-5",
    organizerName: "Sonia Boukhari",
    clubName: "Club Interculturel",
    tags: ["Culture", "International", "Musique", "Gastronomie"],
    speakers: [],
    isHighlight: true,
    status: "upcoming",
  },
  {
    id: "evt-006",
    title: "Conférence : L'Avenir du Droit Numérique",
    description: "Cybercriminalité, RGPD, IA et propriété intellectuelle : les enjeux juridiques du 21ème siècle.",
    longDescription: `À l'heure où le numérique redessine les frontières du droit, cette conférence réunit juristes, chercheurs et professionnels pour analyser les défis légaux émergents. Trois tables rondes couvriront : la réglementation de l'IA, la protection des données personnelles, et la lutte contre la cybercriminalité.\n\nUne opportunité précieuse pour les étudiants en droit et en informatique de comprendre les interactions entre technologie et système juridique.`,
    category: "conference",
    startDate: "2026-06-10T10:00:00",
    endDate: "2026-06-10T16:00:00",
    isMultiDay: false,
    location: "Salle de Conférence B-150",
    building: "Faculté de Droit — RDC",
    coverUrl: COVERS[6],
    gallery: GALLERY.slice(1, 4),
    capacity: 150,
    registeredCount: 92,
    isFree: false,
    price: 0,
    organizerId: "org-6",
    organizerName: "Prof. Nadia Kessous",
    clubName: "Club Droit & Société",
    tags: ["Droit", "Numérique", "RGPD", "IA", "Cybersécurité"],
    speakers: [
      { name: "Me. Tarek Bouzid", role: "Avocat spécialisé IT" },
      { name: "Dr. Sirine Ait Mokhtar", role: "Chercheuse en droit numérique" },
    ],
    isHighlight: false,
    status: "upcoming",
  },
  {
    id: "evt-007",
    title: "Sortie Pédagogique — Musée des Sciences",
    description: "Visite guidée du Musée National des Sciences et Techniques avec exposition spéciale \"Cosmos 2026\".",
    longDescription: `Dans le cadre du programme culturel universitaire, le Club Sciences organise une sortie au Musée National des Sciences. Au programme : visite de l'exposition permanente, accès privilégié à l'exposition temporaire Cosmos 2026 sur l'exploration spatiale, et atelier de réalité virtuelle.\n\nTransport en bus depuis le campus. Places limitées à 45 personnes. Déjeuner libre dans les environs du musée.`,
    category: "sortie",
    startDate: "2026-06-14T08:30:00",
    endDate: "2026-06-14T17:00:00",
    isMultiDay: false,
    location: "Musée National des Sciences",
    building: "Centre-Ville — Avenue Ibn Khaldoun",
    coverUrl: COVERS[7],
    gallery: GALLERY.slice(0, 4),
    capacity: 45,
    registeredCount: 38,
    isFree: false,
    price: 350,
    organizerId: "org-7",
    organizerName: "Omar Bencherif",
    clubName: "Club Sciences & Nature",
    tags: ["Sortie", "Musée", "Sciences", "Espace"],
    speakers: [],
    isHighlight: false,
    status: "upcoming",
  },
  {
    id: "evt-008",
    title: "Workshop : Photographie & Storytelling",
    description: "Maîtrisez l'art de raconter des histoires à travers l'objectif. Théorie, pratique et retouche photo.",
    longDescription: `Ce workshop de 6 heures initie les participants aux fondamentaux de la photographie narrative. Après une session théorique sur la composition, la lumière et le storytelling visuel, les participants sortent en extérieur pour une session de prise de vue guidée sur le campus.\n\nLa journée se termine par une initiation à la retouche sur Lightroom. Apportez votre appareil photo ou smartphone. Niveau débutant accepté.`,
    category: "atelier",
    startDate: "2026-05-30T10:00:00",
    endDate: "2026-05-30T17:00:00",
    isMultiDay: false,
    location: "Studio Photo — Local 15",
    building: "Bâtiment Arts & Communication",
    coverUrl: COVERS[8],
    gallery: GALLERY.slice(2, 6),
    capacity: 20,
    registeredCount: 18,
    isFree: false,
    price: 200,
    organizerId: "org-8",
    organizerName: "Yasmine Saïdi",
    clubName: "Club Photo & Vidéo",
    tags: ["Photographie", "Créativité", "Workshop", "Arts"],
    speakers: [
      { name: "Yasmine Saïdi", role: "Photographe professionnelle" },
    ],
    isHighlight: false,
    status: "upcoming",
  },
  {
    id: "evt-009",
    title: "Forum Emploi & Stage 2026",
    description: "Rencontrez 50+ entreprises partenaires et décrochez votre stage ou premier emploi.",
    longDescription: `Le Forum Emploi & Stage 2026 est le pont entre l'université et le monde professionnel. Plus de 50 entreprises de tous secteurs (tech, finance, industrie, conseil) seront présentes pour des entretiens de recrutement et des présentations de leurs programmes de stage.\n\nServices disponibles sur place : coaching CV, simulations d'entretiens, conférences métiers et remise de prix de la meilleure présentation étudiante.`,
    category: "conference",
    startDate: "2026-06-25T09:00:00",
    endDate: "2026-06-26T17:00:00",
    isMultiDay: true,
    location: "Espace Expositions",
    building: "Bâtiment Principal — Grand Hall",
    coverUrl: COVERS[9],
    gallery: GALLERY.slice(0, 6),
    capacity: 1000,
    registeredCount: 543,
    isFree: true,
    organizerId: "org-1",
    organizerName: "Service Relations Entreprises",
    tags: ["Emploi", "Stage", "Recrutement", "Réseau"],
    speakers: [],
    isHighlight: true,
    status: "upcoming",
  },
  {
    id: "evt-010",
    title: "Concert de Fin d'Année — Formations Musicales",
    description: "Les talents musicaux de l'université sur scène pour un grand concert de clôture de l'année académique.",
    longDescription: `Traditionnellement organisé en fin d'année académique, ce grand concert met en lumière les formations musicales de l'université : orchestre de chambre, chorale universitaire, groupe jazz et ensemble de musiques du monde.\n\nUne soirée de 3 heures ponctuée d'intermèdes poétiques et d'un spectacle de danse contemporaine. Restauration légère disponible. Tenue correcte souhaitée.`,
    category: "culturel",
    startDate: "2026-06-28T20:00:00",
    endDate: "2026-06-28T23:00:00",
    isMultiDay: false,
    location: "Amphithéâtre en Plein Air",
    building: "Jardin Central — Campus Nord",
    coverUrl: COVERS[10],
    gallery: GALLERY.slice(1, 5),
    capacity: 600,
    registeredCount: 421,
    isFree: true,
    organizerId: "org-5",
    organizerName: "Dir. des Activités Culturelles",
    tags: ["Musique", "Concert", "Culture", "Fin d'Année"],
    speakers: [],
    isHighlight: true,
    status: "upcoming",
  },
  {
    id: "evt-011",
    title: "Séminaire : Entrepreneuriat et Start-up",
    description: "De l'idée à la levée de fonds : les clés pour lancer sa start-up dès l'université.",
    longDescription: `Ce séminaire d'une journée réunit fondateurs de start-ups, investisseurs et coachs pour partager leur expérience avec les étudiants entrepreneurs. Sessions plénières le matin, ateliers thématiques l'après-midi (pitch deck, financements, juridique, marketing growth).\n\nChaque participant repart avec un plan d'action personnalisé et l'accès à un réseau de mentors.`,
    category: "conference",
    startDate: "2026-06-05T09:00:00",
    endDate: "2026-06-05T18:00:00",
    isMultiDay: false,
    location: "Salle de Conférence C-200",
    building: "Incubateur Universitaire",
    coverUrl: COVERS[11],
    gallery: GALLERY.slice(0, 4),
    capacity: 80,
    registeredCount: 65,
    isFree: false,
    price: 500,
    organizerId: "org-2",
    organizerName: "Walid Benamar",
    clubName: "Club Entrepreneuriat",
    tags: ["Entrepreneuriat", "Start-up", "Business", "Innovation"],
    speakers: [
      { name: "Walid Benamar", role: "Fondateur & CEO" },
      { name: "Mme. Hind Touati", role: "Investisseur Angel" },
    ],
    isHighlight: false,
    status: "upcoming",
  },
  {
    id: "evt-012",
    title: "Championnat d'Échecs Universitaire",
    description: "Affrontez les meilleurs joueurs d'échecs de l'université lors du championnat annuel en 7 rondes.",
    longDescription: `Le Championnat Universitaire d'Échecs est organisé selon le système suisse en 7 rondes de 90 minutes chacune. Ouvert à tous les niveaux, il accueille aussi bien les débutants que les joueurs classés.\n\nTrophées pour les 5 premiers, médailles pour tous les participants. Arbitre officiel FIDE. Inscription individuelle, aucun pré-requis de niveau.`,
    category: "competition",
    startDate: "2026-06-12T09:00:00",
    endDate: "2026-06-13T18:00:00",
    isMultiDay: true,
    location: "Salle Polyvalente D-101",
    building: "Bâtiment D — 1er étage",
    coverUrl: COVERS[4],
    gallery: GALLERY.slice(3, 6),
    capacity: 64,
    registeredCount: 47,
    isFree: true,
    organizerId: "org-9",
    organizerName: "Fares Ziani",
    clubName: "Club Échecs & Stratégie",
    tags: ["Échecs", "Stratégie", "Compétition", "Tournoi"],
    speakers: [],
    isHighlight: false,
    status: "upcoming",
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  conference: "Conférence",
  atelier: "Atelier",
  competition: "Compétition",
  sortie: "Sortie",
  culturel: "Culturel",
  sportif: "Sportif",
  autre: "Autre",
};

export const CATEGORY_COLORS: Record<string, string> = {
  conference: "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  atelier: "bg-violet-500/15 text-violet-600 dark:text-violet-400",
  competition: "bg-rose-500/15 text-rose-600 dark:text-rose-400",
  sortie: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
  culturel: "bg-amber-500/15 text-amber-600 dark:text-amber-400",
  sportif: "bg-cyan-500/15 text-cyan-600 dark:text-cyan-400",
  autre: "bg-slate-500/15 text-slate-600 dark:text-slate-400",
};

export const LOCATIONS = [
  "Amphithéâtre Principal",
  "Bâtiment A",
  "Bâtiment Tech",
  "Complexe Sportif",
  "Aula Magna",
  "Faculté de Droit",
  "Incubateur Universitaire",
];
